# Generated by Django 4.1.7 on 2023-03-12 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_explanation_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="modified_time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="modified_time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="explanation",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="explanation",
            old_name="modified_time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="modified_time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="created_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="modified_time",
            new_name="updated_at",
        ),
    ]
