# Generated by Django 4.1.7 on 2023-03-14 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_rename_created_time_answer_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["difficulty", "-created_at"]},
        ),
    ]
