# Generated by Django 4.1.7 on 2023-03-15 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0004_alter_problem_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestCase",
        ),
    ]
