# Generated by Django 4.1.7 on 2023-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_delete_testcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("stack_queue", "스택&큐"),
                    ("brute_force", "완전 탐색"),
                    ("graph_search", "그래프 탐색"),
                    ("dynamic_programming", "동적 계획법"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[("1", "쉬움"), ("2", "보통"), ("3", "어려움")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
