# Generated by Django 4.1.7 on 2023-03-16 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0008_alter_problem_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={},
        ),
    ]
